# Generated by Django 4.2.25 on 2025-11-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_doctorprofile_latitude_doctorprofile_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_CLINIC", "In-Clinic"), ("ONLINE", "Online")],
                        default="IN_CLINIC",
                        max_length=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="accounts.doctorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "unique_together": {("doctor", "start_time", "end_time")},
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING_PAYMENT",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="UNPAID",
                        max_length=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "patient_notes",
                    models.TextField(
                        blank=True, help_text="Symptoms or reason for visit.", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The 'booking_date' for the ML model.",
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, help_text="The 'message_sent' for the ML model."
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When patient hit 'I am here' in-clinic.",
                        null=True,
                    ),
                ),
                (
                    "consultation_start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When doctor hits 'Start' button.",
                        null=True,
                    ),
                ),
                (
                    "consultation_end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When doctor hits 'End' button.",
                        null=True,
                    ),
                ),
                ("video_call_link", models.URLField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="accounts.patient",
                    ),
                ),
                (
                    "time_slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="appointments.timeslot",
                    ),
                ),
            ],
            options={
                "ordering": ["time_slot__start_time"],
            },
        ),
    ]
