# Generated by Django 4.2.25 on 2026-01-10 08:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique appointment reference number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("in_clinic", "In-Clinic"),
                            ("online", "Online"),
                            ("both", "Both"),
                        ],
                        default="in_clinic",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paypal", "PayPal"),
                            ("razorpay", "Razorpay"),
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("free", "Free/Waived"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "payment_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True, help_text="Patient's symptoms or reason for visit"
                    ),
                ),
                (
                    "patient_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from patient"
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, help_text="Doctor's notes/observations"
                    ),
                ),
                ("prescription", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("patient_request", "Patient Request"),
                            ("doctor_unavailable", "Doctor Unavailable"),
                            ("emergency", "Emergency"),
                            ("rescheduled", "Rescheduled"),
                            ("no_show", "No Show"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cancellation_notes", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_start_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("consultation_end_time", models.DateTimeField(blank=True, null=True)),
                ("video_call_link", models.URLField(blank=True, null=True)),
                ("video_call_id", models.CharField(blank=True, max_length=100)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "family_member",
                    models.ForeignKey(
                        help_text="The family member this appointment is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="accounts.familymember",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("in_clinic", "In-Clinic"),
                            ("online", "Online"),
                            ("both", "Both"),
                        ],
                        default="in_clinic",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="available",
                        max_length=15,
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty to use doctor's default fee",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="accounts.doctorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "time_slots",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(help_text="Rating from 1 to 5"),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField(blank=True)),
                (
                    "wait_time_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bedside_manner_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_verified", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("doctor_response", models.TextField(blank=True)),
                ("doctor_response_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "favorite_doctors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(max_length=15)),
                ("to_status", models.CharField(max_length=15)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "appointment_status_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="time_slot",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment",
                to="appointments.timeslot",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                help_text="The user who booked the appointment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["doctor", "date"], name="time_slots_doctor__ecdbf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(fields=["status"], name="time_slots_status_9ec354_idx"),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["date", "status"], name="time_slots_date_ca7413_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("doctor", "date", "start_time")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["doctor", "rating"], name="reviews_doctor__821800_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoritedoctor",
            unique_together={("user", "doctor")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["user", "status"], name="appointment_user_id_9e7c3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "status"], name="appointment_doctor__45f502_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_number"], name="appointment_appoint_e7d91b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_9fecd6_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["created_at"], name="appointment_created_e3a5d5_idx"
            ),
        ),
    ]
