# Generated by Django 4.2.25 on 2026-01-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triage_category",
                    models.CharField(
                        choices=[
                            ("CHEST_PAIN", "Chest Pain"),
                            ("BREATHING", "Breathing Difficulty"),
                            ("INJURY", "Broken Bone / Injury"),
                            ("BLEEDING", "Severe Bleeding"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("patient_notes", models.TextField(blank=True, null=True)),
                ("user_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("user_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SEARCHING", "Searching for Doctor"),
                            ("REQUESTED", "Request Sent to Doctor"),
                            ("ACCEPTED", "Accepted by Doctor"),
                            ("CANCELLED", "Cancelled by Patient"),
                        ],
                        default="SEARCHING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_cases",
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "linked_appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_requests",
                        to="accounts.familymember",
                    ),
                ),
            ],
        ),
    ]
