# Generated by Django 4.2.25 on 2026-01-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emergencyrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelTable(
            name="emergencyrequest",
            table="emergency_requests",
        ),
    ]
